version: '3.7'

services:
   db:
    image: registry.zyca.vn:5000/mysql-server:1.4.0
    container_name: db_prd
    build:
        dockerfile: Db_prd.Dockerfile
        context: .
    environment:
        MYSQL_ROOT_PASSWORD: root_inno2021
        MYSQL_USER: inno2021
        MYSQL_PASSWORD: inno2021@abc
        TZ: Asia/Ho_Chi_Minh
    networks:
        - inno_net
    volumes:
        - inno_vol_prd:/var/lib/mysql
    restart: always
    ports:
        - "3306:3306"

   clash_backend:
    image: registry.zyca.vn:5000/clash_backend:1.4.2
    container_name: clash_backend_prd
    build:
        dockerfile: Backend.Dockerfile
        context: .
    environment:
        ASPNETCORE_ENVIRONMENT: Production
        TZ: Asia/Ho_Chi_Minh
    restart: unless-stopped
    ports:
        - "8081:80"
    networks:
        - inno_net
    volumes:
        - resources:/app/Resources

volumes:
    resources:
        external: true
    inno_vol_prd:
        external: true
networks:
    inno_net:
        external: true
      